---
shared:
  image: node:6

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - install: echo install
      - test: echo test
  publish:
    requires: main
    steps:
      - date
    secrets:
      - NPM_TOKEN
